---
kind: pipeline
type: kubernetes
name: linter

platform:
  os: linux
  arch: amd64

steps:
- name: markdown lint
  commands:
  - markdownlint *.md
  image: docker.io/volkerraschek/markdownlint:0.30.0
  resources:
    limits:
      cpu: 50
      memory: 50M

- name: email-notification
  environment:
    PLUGIN_HOST:
      from_secret: smtp_host
    PLUGIN_USERNAME:
      from_secret: smtp_username
    PLUGIN_PASSWORD:
      from_secret: smtp_password
    PLUGIN_FROM:
      from_secret: smtp_mail_address
  image: docker.io/drillster/drone-email:latest
  resources:
    limits:
      cpu: 50
      memory: 25M
  when:
    status:
    - changed
    - failure

trigger:
  event:
    exclude:
    - tag

---
kind: pipeline
type: docker
name: archlinux

platform:
  os: linux
  arch: amd64

steps:
- name: archlinux
  image: docker.io/volkerraschek/build-image:latest
  commands:
  - ./build.sh archlinux latest
  environment:
    CONTAINER_IMAGE_REGISTRY_PASSWORD:
      from_secret: container_image_registry_password
  volumes:
  - name: docker_socket
    path: /var/run/docker.sock

- name: notify
  image: drillster/drone-email
  environment:
    PLUGIN_HOST:
      from_secret: smtp_host
    PLUGIN_USERNAME:
      from_secret: smtp_username
    PLUGIN_PASSWORD:
      from_secret: smtp_password
    PLUGIN_FROM:
      from_secret: smtp_mail_address
  when:
    status:
    - changed
    - failure

trigger:
  when:
    branch:
    - master
    event:
    - push
    - cron

volumes:
- name: docker_socket
  host:
    path: /var/run/docker.sock

---
kind: pipeline
type: docker
name: centos

platform:
  os: linux
  arch: amd64

steps:
- name: centos7
  image: docker.io/volkerraschek/build-image:latest
  commands:
  - ./build.sh centos 7
  environment:
    CONTAINER_IMAGE_REGISTRY_PASSWORD:
      from_secret: container_image_registry_password
  volumes:
  - name: docker_socket
    path: /var/run/docker.sock

- name: notify
  image: drillster/drone-email
  environment:
    PLUGIN_HOST:
      from_secret: smtp_host
    PLUGIN_USERNAME:
      from_secret: smtp_username
    PLUGIN_PASSWORD:
      from_secret: smtp_password
    PLUGIN_FROM:
      from_secret: smtp_mail_address
  when:
    status:
    - changed
    - failure

trigger:
  when:
    branch:
    - master
    event:
    - push
    - cron

volumes:
- name: docker_socket
  host:
    path: /var/run/docker.sock

---
kind: pipeline
type: docker
name: debian

platform:
  os: linux
  arch: amd64

steps:
- name: 8-slim
  image: docker.io/volkerraschek/build-image:latest
  commands:
  - ./build.sh debian 8-slim
  environment:
    CONTAINER_IMAGE_REGISTRY_PASSWORD:
      from_secret: container_image_registry_password
  volumes:
  - name: docker_socket
    path: /var/run/docker.sock

- name: 9-slim
  image: docker.io/volkerraschek/build-image:latest
  commands:
  - ./build.sh debian 9-slim
  environment:
    CONTAINER_IMAGE_REGISTRY_PASSWORD:
      from_secret: container_image_registry_password
  volumes:
  - name: docker_socket
    path: /var/run/docker.sock

- name: 10-slim
  image: docker.io/volkerraschek/build-image:latest
  commands:
  - ./build.sh debian 10-slim
  environment:
    CONTAINER_IMAGE_REGISTRY_PASSWORD:
      from_secret: container_image_registry_password
  volumes:
  - name: docker_socket
    path: /var/run/docker.sock

- name: 11-slim
  image: docker.io/volkerraschek/build-image:latest
  commands:
  - ./build.sh debian 11-slim
  environment:
    CONTAINER_IMAGE_REGISTRY_PASSWORD:
      from_secret: container_image_registry_password
  volumes:
  - name: docker_socket
    path: /var/run/docker.sock

- name: notify
  image: drillster/drone-email
  environment:
    PLUGIN_HOST:
      from_secret: smtp_host
    PLUGIN_USERNAME:
      from_secret: smtp_username
    PLUGIN_PASSWORD:
      from_secret: smtp_password
    PLUGIN_FROM:
      from_secret: smtp_mail_address
  when:
    status:
    - changed
    - failure

trigger:
  when:
    branch:
    - master
    event:
    - push
    - cron

volumes:
- name: docker_socket
  host:
    path: /var/run/docker.sock

---
kind: pipeline
type: docker
name: fedora

platform:
  os: linux
  arch: amd64

steps:
- name: fedora-33
  image: docker.io/volkerraschek/build-image:latest
  commands:
  - ./build.sh fedora 33
  environment:
    CONTAINER_IMAGE_REGISTRY_PASSWORD:
      from_secret: container_image_registry_password
  volumes:
  - name: docker_socket
    path: /var/run/docker.sock

- name: fedora-34
  image: docker.io/volkerraschek/build-image:latest
  commands:
  - ./build.sh fedora 34
  environment:
    CONTAINER_IMAGE_REGISTRY_PASSWORD:
      from_secret: container_image_registry_password
  volumes:
  - name: docker_socket
    path: /var/run/docker.sock

- name: notify
  image: drillster/drone-email
  environment:
    PLUGIN_HOST:
      from_secret: smtp_host
    PLUGIN_USERNAME:
      from_secret: smtp_username
    PLUGIN_PASSWORD:
      from_secret: smtp_password
    PLUGIN_FROM:
      from_secret: smtp_mail_address
  when:
    status:
    - changed
    - failure

trigger:
  when:
    branch:
    - master
    event:
    - push
    - cron

volumes:
- name: docker_socket
  host:
    path: /var/run/docker.sock

---
kind: pipeline
type: docker
name: ubuntu

platform:
  os: linux
  arch: amd64

steps:
- name: ubuntu-16.04
  image: docker.io/volkerraschek/build-image:latest
  commands:
  - ./build.sh ubuntu 16.04
  environment:
    CONTAINER_IMAGE_REGISTRY_PASSWORD:
      from_secret: container_image_registry_password
  volumes:
  - name: docker_socket
    path: /var/run/docker.sock

- name: ubuntu-18.04
  image: docker.io/volkerraschek/build-image:latest
  commands:
  - ./build.sh ubuntu 18.04
  environment:
    CONTAINER_IMAGE_REGISTRY_PASSWORD:
      from_secret: container_image_registry_password
  volumes:
  - name: docker_socket
    path: /var/run/docker.sock

- name: ubuntu-20.04
  image: docker.io/volkerraschek/build-image:latest
  commands:
  - ./build.sh ubuntu 20.04
  environment:
    CONTAINER_IMAGE_REGISTRY_PASSWORD:
      from_secret: container_image_registry_password
  volumes:
  - name: docker_socket
    path: /var/run/docker.sock

- name: notify
  image: drillster/drone-email
  environment:
    PLUGIN_HOST:
      from_secret: smtp_host
    PLUGIN_USERNAME:
      from_secret: smtp_username
    PLUGIN_PASSWORD:
      from_secret: smtp_password
    PLUGIN_FROM:
      from_secret: smtp_mail_address
  when:
    status:
    - changed
    - failure

trigger:
  when:
    branch:
    - master
    event:
    - push
    - cron

volumes:
- name: docker_socket
  host:
    path: /var/run/docker.sock

---
kind: pipeline
type: kubernetes
name: sync

platform:
  os: linux
  arch: amd64

steps:
- name: github
  image: docker.io/appleboy/drone-git-push:latest
  resources:
    limits:
      cpu: 50
      memory: 25M
  settings:
    branch: master
    remote: ssh://git@github.com/volker-raschek/latex-docker.git
    force: true
    ssh_key:
      from_secret: ssh_key

- name: email-notification
  environment:
    PLUGIN_HOST:
      from_secret: smtp_host
    PLUGIN_USERNAME:
      from_secret: smtp_username
    PLUGIN_PASSWORD:
      from_secret: smtp_password
    PLUGIN_FROM:
      from_secret: smtp_mail_address
  image: docker.io/drillster/drone-email:latest
  resources:
    limits:
      cpu: 50
      memory: 25M
  when:
    status:
    - changed
    - failure

trigger:
  event:
  - push
  repo:
  - volker.raschek/latex-docker
